### ISSUE TITLE
org.altbeacon.beacon.service.BeaconService$1.onLeScan FATAL EXCEPTION

### ISSUE THREAD

**Issue by Keith3679** [AltBeacon/spec#25] opened 2015-08-31 15:38 UTC
Fellow AltBeacon Developers,

I'm seeing the following AndroidRuntime FATAL EXCEPTION: main in ADB Logcat after I RangeBeacons for approximately 8 hours.  It appears to only happen when my app is in an area of high beacon congestion, IE in a lab etc.  If it sits in a quiet area, we do not see this exception...

![crash](https://cloud.githubusercontent.com/assets/12281546/9582457/74175920-4fd3-11e5-8ff5-29234bde7cf4.jpg)

I'm not seeing any Exceptions in my code elseware nor am I seeing the above Exception.  The App just dies and falls out of the sky without any warning.

Anybody have an insight as to what the problem could be?

Thanks

Keith

**Comment by davidgyoung** [comment] 2015-08-31 16:01
Can you please tell us what version of the library you are running?

**Comment by Keith3679** [comment] 2015-08-31 16:25
David,

I'm using version 2.1.4 of the Xamarin AltBeacon NuGet...

https://components.xamarin.com/view/android-altbeacon-library

**Comment by davidgyoung** [comment] 2015-08-31 16:49
This is a duplicate of this issue: https://github.com/AltBeacon/android-beacon-library/pull/217

It was fixed in Android Beacon Library version 2.3.1 https://github.com/AltBeacon/android-beacon-library/releases/tag/2.3.1

Your best bet is to try to get the Xamarin wrapper updated.

**Closed as completed by davidgyoung** 2015-08-31 16:49 UTC

**Comment by Keith3679** [comment] 2015-08-31 17:01
Thanks David!
